# Generated by Django 5.2.6 on 2026-03-14 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('docker_image', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='queued', max_length=20)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge_task', to='exams.answer')),
            ],
        ),
    ]
